Added questions on how to add easyfix, mentor
redhat-openstack/easyfix pull request #2
Opened 2017-06-29 16:12 UTC by chkumar246

2017-06-29 16:21 UTC, javierpena commented
👍

2017-06-29 16:25 UTC, amoralej commented on README.rst
> +* Join the `RDO mailing list <https://www.redhat.com/mailman/listinfo/rdo-list>`
I'd add a reference to https://www.rdoproject.org/documentation/onboarding/ or https://www.rdoproject.org/documentation/rdo-packaging/

2017-06-29 16:28 UTC, apevec requested changes

2017-06-29 16:28 UTC, apevec commented on README.rst
> +* It would be great how i can reproduce it.
* If possible add steps how it can be reproduced.

2017-06-29 16:28 UTC, apevec commented on README.rst
> +* Adding your IRC link so that people can reach out for help.
* Add your IRC nickname...

2017-06-29 16:28 UTC, apevec commented on README.rst
> +I want to add easyfix, How can i do that?
s/i/I/

2017-06-29 16:28 UTC, apevec commented on README.rst
> +Still confused, What should i do?
s/i/I/

2017-06-29 16:28 UTC, apevec commented on README.rst
> +* OR you can join #rdo IRC channel on Freenode server and Say hello.
s/server//
s/Say/say/

2017-06-29 16:28 UTC, apevec commented on README.rst
> +* We are always there, Happy to Help.
s/Happy/happy/ s/Help/help/

2017-06-29 16:28 UTC, apevec commented on README.rst
> +* Follow I want to add easyfix, How can i do that?.
s/i/I/

2017-06-29 16:42 UTC, yac submitted a review, later dismissed
Got some suggestions ;)

2017-06-29 16:42 UTC, yac commented on README.rst
> +It is a collection of easyfix or low hanging fruits issues for RDO Project.
of easy fixes or low hanging fruit issues

2017-06-29 16:42 UTC, yac commented on README.rst
> +I am new to RDO Project, How can i contribute?
s/ i / I /

2017-06-29 16:42 UTC, yac commented on README.rst
> +RDO Project Easyfix
I suggest naming README.md which github nicely renders as Markdown including links and... use Markdown ;)

2017-06-29 16:42 UTC, yac commented on README.rst
> +* You can check the issues and assign to it yourself.
You can check [Issues](https://github.com/redhat-openstack/easyfix/issues) and assign some to yourself.

2017-06-29 16:42 UTC, yac commented on README.rst
> +* If you are not able understand, join the IRC channel #rdo on Freenode server.
If you aren't able understand, join the IRC channel `#rdo` on Freenode server.

2017-06-29 16:42 UTC, yac commented on README.rst
> +* Each issue contains mentor IRC nick.
Mentor

2017-06-29 16:42 UTC, yac commented on README.rst
> +* Ping the Mentor regarding the issue, S/He will help to move forward.
will help you move forward

2017-06-29 16:42 UTC, yac commented on README.rst
> +* Go to issues and file the issue.
[Issues](https://github.com/redhat-openstack/easyfix/issues) link for convenience

2017-06-29 16:42 UTC, yac commented on README.rst
> +* Please add tag as project name.
Please add `[PROJECT] ` prefix to Issue name. ?

Alternatively, labels can be used, but I guess this is clearer on the first sight.

2017-06-29 16:42 UTC, yac commented on README.rst
> +* It would be great how i can reproduce it.
Describe howto reproduce the issue.

2017-06-29 16:42 UTC, yac commented on README.rst
> +* Add links which will help to understand the problem.
Add links to help understand the problem.

2017-06-29 16:42 UTC, yac commented on README.rst
> +* Adding your IRC link so that people can reach out for help.
s/Adding/Add/ for consistency with above point

2017-06-29 16:42 UTC, yac commented on README.rst
> +* Once problem is reproduced, where they can submit the changes.
Describe where/how to submit required changes.

2017-06-29 16:42 UTC, yac commented on README.rst
> +Still confused, What should i do?
s/ i / I /

2017-06-29 16:42 UTC, yac commented on README.rst
> +* Join the `RDO mailing list <https://www.redhat.com/mailman/listinfo/rdo-list>`
Join the [RDO mailing list](https://www.redhat.com/mailman/listinfo/rdo-list).

2017-06-29 16:42 UTC, yac commented on README.rst
> +* Follow I want to add easyfix, How can i do that?.
s/ i / I /

2017-06-29 16:42 UTC, yac commented on README.rst
> +Mentors
Mentors (IRC nicks)

2017-06-29 16:42 UTC, yac commented on README.rst
> +* Jakub Ruzicka (jruzicka)
* Jakub Ruzicka (`jruzicka`)
(distinguish `nick` with monospace)

2017-06-30 14:34 UTC, apevec approved these changes

2017-06-30 14:34 UTC, merged